# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  database: git_new_dev
  host: localhost

test:
  adapter: postgresql
  database: git_new_test
  host: localhost

production:
  adapter: postgresql
  database: git_new_dev
  host: localhost